# Generated by Django 2.2.5 on 2019-10-26 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191018_2032'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Personas',
            new_name='Persona',
        ),
    ]
